### ISSUE TITLE
parseReader not found error

### ISSUE THREAD

**Issue by 573** [ssilverman/snowy-json#16]
With the [Main](https://github.com/ssilverman/snowy-json/blob/66bf734/src/main/java/com/qindesign/json/schema/Main.java) and the [artifact](https://github.com/ssilverman/snowy-json/blob/66bf734/README.md#using-snow-in-your-own-projects) added to my pom.xml I get:

>Exception in thread "main" java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseReader(java.io.Reader)'
	at com.qindesign.json.schema.JSON.parse(JSON.java:132)
	at com.qindesign.json.schema.JSON.parse(JSON.java:119)
	at com.qindesign.json.schema.JSON.parse(JSON.java:91)
	at de.elster.testing.common.validator.Main.main(Main.java:86)

Does that mean to use the `Main` as an example I needed to copy all classes over ?
How are the [classes](https://github.com/ssilverman/snowy-json/tree/66bf734/src/main/java/com/qindesign/json/schema) meant to be used in my project ? There aren't any class files when adding the artifact to the pom and rebuilding my project.

I guess I am being very noob or confused here.

Wait, is the scope of it being a scaffold for how to integrate JSON validation into mvn ? As such it does an excellent job !

**Comment by 573** [comment]
It seems as though my pom involved `gson` version `2.8.2` and explicitly adding
```xml
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.8.6</version>
</dependency>
```
fixed it, meaning the `Main` from this repo artifact itself just plain worked without copying over any other classes.

![grafik](https://user-images.githubusercontent.com/123878/189346090-e4a92e88-6850-4df2-874c-e56110086dcb.png)

Thx for an amazing project !
